DROP TABLE IF EXISTS PLAYERS;

CREATE TABLE PLAYERS(
	PlayerID	INT		NOT NULL AUTO_INCREMENT,
	Alias		CHAR(20)	NOT NULL,
	FirstName	CHAR(20)	NOT NULL,
	LastName	CHAR(20)	NOT NULL,
	Email		CHAR(30)	NOT NULL,
	CONSTRAINT	PlayerPK	PRIMARY KEY(PlayerID)
);
