DROP TABLE IF EXISTS ITEM_DESCRIPTIONS;

CREATE TABLE ITEM_DESCRIPTIONS(
	ItemID		INT					NOT NULL,
	DescriptionID	INT					NOT NULL
		AUTO_INCREMENT,
	Rarity		ENUM('Common', 'Rare', 'Legendary')	NOT NULL
		DEFAULT 'Common',
	Value		MEDIUMINT UNSIGNED			NOT NULL
		DEFAULT 0,
	FlavorText	TEXT(100)				NOT NULL,
	CONSTRAINT	DescriptionPK	PRIMARY KEY(DescriptionID),
	CONSTRAINT	UniqueFK	UNIQUE(ItemID),
	CONSTRAINT	ItemFK		FOREIGN KEY(ItemID)
				REFERENCES ITEMS(ItemID)
					ON UPDATE NO ACTION
					ON DELETE CASCADE
);
