DROP TABLE IF EXISTS SERVERS_PLAYERS_INT;

CREATE TABLE SERVERS_PLAYERS_INT(
	ServerID	INT	NOT NULL,
	PlayerID	INT	NOT NULL,
	CONSTRAINT	SPIntPK 	PRIMARY KEY(ServerID, PlayerID),
	CONSTRAINT	SPInt_ServerFK	FOREIGN KEY(ServerID)
				REFERENCES SERVERS(ServerID)
					ON UPDATE NO ACTION
					ON DELETE CASCADE,
	CONSTRAINT	SPInt_PlayerFK	FOREIGN KEY(PlayerID)
				REFERENCES PLAYERS(PlayerID)
					ON UPDATE NO ACTION
					ON DELETE CASCADE
);
