DROP TABLE IF EXISTS CHARACTERS;

CREATE TABLE CHARACTERS(
	PlayerID	INT					NOT NULL,
	CharacterID	INT					NOT NULL AUTO_INCREMENT,
	Name		CHAR(20)				NOT NULL,
	Level		TINYINT UNSIGNED			NOT NULL,
	Sex		ENUM('Male', 'Female')			NOT NULL,
	Class		ENUM('Mage', 'Warrior', 'Priest')	NOT NULL,
	CONSTRAINT	CharacterPK	PRIMARY KEY(CharacterID),
	CONSTRAINT	PlayerFK	FOREIGN KEY(PlayerID)
				REFERENCES PLAYERS(PlayerID)
					ON UPDATE NO ACTION
					ON DELETE CASCADE
);
