DROP TABLE IF EXISTS CHARACTERS_ITEMS_INT;

CREATE TABLE CHARACTERS_ITEMS_INT(
	CharacterID	INT	NOT NULL,
	ItemID		INT	NOT NULL,
	CONSTRAINT	CIInt_PK		PRIMARY KEY(CharacterID, ItemID),
	CONSTRAINT	CIInt_CharactersFK	FOREIGN KEY(CharacterID)
				REFERENCES CHARACTERS(CharacterID)
					ON UPDATE NO ACTION
					ON DELETE CASCADE,
	CONSTRAINT	CIInt_ItemsFK		FOREIGN KEY(ItemID)
				REFERENCES ITEMS(ItemID)
					ON UPDATE NO ACTION
                                        ON DELETE CASCADE
);
