DROP VIEW IF EXISTS PLAYER_CHARACTER;

CREATE VIEW PLAYER_CHARACTER AS
	SELECT	P.Alias AS 'Player',
		C.Name	AS 'Character',
		C.Level
	FROM PLAYERS P JOIN CHARACTERS C
		ON P.PlayerID = C.PlayerID
	ORDER BY P.PlayerID ASC
;
