INSERT INTO SERVERS (Name, Type) VALUES ('Big Boy', 'PvP');
INSERT INTO SERVERS (Name, Type) VALUES ('Big Girl', 'PvP');
INSERT INTO SERVERS (Name, Type) VALUES ('Lil Boy', 'PvE');
INSERT INTO SERVERS (Name, Type) VALUES ('Lil Girl', 'PvE');
INSERT INTO SERVERS (Name, Type) VALUES ('War Zone', 'PvP');
INSERT INTO SERVERS (Name, Type) VALUES ('Carebear', 'PvE');
INSERT INTO SERVERS (Name, Type) VALUES ('Math Club', 'PvP');
INSERT INTO SERVERS (Name, Type) VALUES ('Byte Club', 'PvP');
INSERT INTO SERVERS (Name, Type) VALUES ('WOU', 'PvE');
INSERT INTO SERVERS (Name, Type) VALUES ('Daggers Point', 'Pvp');
INSERT INTO SERVERS (Name, Type) VALUES ('Stared Twins', 'PvE');
INSERT INTO SERVERS (Name, Type) VALUES ('Lore Hunters', 'PvE');
INSERT INTO SERVERS (Name, Type) VALUES ('Battle Ground', 'PvP');
INSERT INTO SERVERS (Name, Type) VALUES ('Dungeon Run', 'PvE');
INSERT INTO SERVERS (Name, Type) VALUES ('Gank Town', 'PvP');
INSERT INTO SERVERS (Name, Type) VALUES ('Hell', 'PvP');
INSERT INTO SERVERS (Name, Type) VALUES ('Heaven', 'PvE');
INSERT INTO SERVERS (Name, Type) VALUES ('PCC', 'PvE');
INSERT INTO SERVERS (Name, Type) VALUES ('PSU', 'PvP');
INSERT INTO SERVERS (Name, Type) VALUES ('OSU', 'PvP');
